### ISSUE TITLE
Make title and description more informative

### ISSUE THREAD

**Issue by gbowerman** [Azure-Samples/Azure-PostgreSQL-Resilience-Architecture#3]
Can you change the title from" "Terraform Azure Setup" to something like: "Azure-PostgreSQL Resilient Architecture - Terraform"

and the description underneath from "This guide provides step-by-step instructions to set up and deploy your infrastructure on Azure using Terraform." to something that explains what the solution is, e.g., a reference implementation for a resilient deployment of Azure Database for PostgreSQL in Terraform that leverages high available and distributes read load using read replicas etc. 

It will be useful for anyone reading the Readme to understand what this is, what the benefits are at the beginning, and also links for further reading at the end.

**Comment by gkasar** [comment]
I have added description related to the architecture and its specifics
